language: php

php:
  - 5.6
  - 7.0
  - hhvm

services:
  - mysql

before_script:
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
  - sudo sed -i -e "s,/var/www,$(pwd)/public,g" /etc/apache2/sites-available/default
  - sudo a2enmod rewrite
  - sudo /etc/init.d/apache2 restart
  - sudo sed -i -e "/DocumentRoot/i\ServerName eestec.local" /etc/apache2/sites-available/default
  - echo "127.0.0.1 eestec.local" | sudo tee -a /etc/hosts
  - sudo /etc/init.d/apache2 restart

  - sudo apt-get install libxss1 libappindicator1 libindicator7 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - sudo apt-get install -f

  - sudo apt-get install xvfb
  - sudo apt-get install unzip
  - wget -N http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - sudo mv -f chromedriver /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver

  - curl -s http://getcomposer.org/installer | php
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - php composer.phar install --dev
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://selenium-release.storage.googleapis.com/2.49/selenium-server-standalone-2.49.1.jar"
  - "java -jar selenium-server-standalone-2.49.1.jar > /dev/null &"
  - sleep 5
  - mysql -e 'create database ep_test;'
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get -y update
  - sudo apt-get -y install nodejs
  - sudo npm install -g grunt-cli
  - sudo npm install -g bower
  - sudo npm install
  - bower install
  - grunt
  - mv .env.travis .env
  - php artisan migrate --force
  - php artisan db:seed --force
  - php artisan db:seed --force --class=FakeDataSeeder
  - chmod -R 777 storage
  - php artisan key:generate

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

script:
  - ./vendor/bin/behat
  - phpunit --coverage-clover=coverage.clover