language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

script: phpunit --coverage-clover=coverage.clover
